image: biggora/gitlab-zone
# services:
#  - mariadb
#  - mysql
#  - postgres
#  - redis
#  - mongo
#  - rethinkdb
#  - arangodb
#  - neo4j

variables:
  MYSQL_USER: "test"
  MYSQL_PASSWORD: "test"
  MYSQL_DATABASE: "test"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  POSTGRES_USER: "test"
  POSTGRES_PASSWORD: "test"
  POSTGRES_DB: "test"
  ARANGO_ROOT_PASSWORD: "test"
  ARANGO_NO_AUTH: "1"
  ARANGO_RANDOM_ROOT_PASSWORD: "0"

before_script:
    - cat /etc/hosts | grep 172

stages:
    - test

dbs-tests:
  services:
      - mariadb
      - postgres
      - redis
      - mongo
  stage: test
  script:
      - npm install --save-dev
      - make test-sqlite
      - make test-mysql
      - make test-mariadb
      - make test-redis
      - make test-mongo
  only:
      - master
  tags:
      - node
