image: biggora/gitlab-zone
# services:
#  - mariadb
#  - mysql
#  - postgres
#  - redis
#  - mongo
#  - rethinkdb
#  - arangodb
#  - neo4j

variables:
  MYSQL_USER: "test"
  MYSQL_PASSWORD: "test"
  MYSQL_DATABASE: "test"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  POSTGRES_USER: "test"
  POSTGRES_PASSWORD: "test"
  POSTGRES_DB: "test"
  ARANGO_ROOT_PASSWORD: "test"
  ARANGO_NO_AUTH: "1"
  ARANGO_RANDOM_ROOT_PASSWORD: "0"

before_script:
    - cat /etc/hosts | grep 172

stages:
    - test

redis:
  services:
      - redis
  stage: test
  script:
      - npm install bluebird mocha should redis
      - make test-redis
  only:
      - master
  tags:
      - node
      
sqlite:
  stage: test
  script:
      - npm install bluebird mocha should sqlite3 
      - make test-sqlite
  only:
      - master
  tags:
      - node
      
mariadb:
  services:
      - mariadb
  stage: test
  script:
      - npm install bluebird mocha should mysql 
      - make test-mysql
  only:
      - master
  tags:
      - node
      
mongo:
  services:
      - mongo
  stage: test
  script:
      - npm install bluebird mocha should mongodb 
      - make test-mongo
  only:
      - master
  tags:
      - node