image: biggora/gitlab-zone
services:
  - mariadb
  - mysql
  - postgres
  - redis
  - mongo
  - rethinkdb
  - arangodb
  - neo4j

variables:
  MYSQL_USER: "test"
  MYSQL_PASSWORD: "test"
  MYSQL_DATABASE: "test"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  POSTGRES_USER: "test"
  POSTGRES_PASSWORD: "test"
  POSTGRES_DB: "test"
  ARANGO_ROOT_PASSWORD: "test"
  ARANGO_NO_AUTH: "1"
  ARANGO_RANDOM_ROOT_PASSWORD: "0"

before_script:
    - cat /etc/hosts | grep 172

stages:
    - test

sqlite:
  stage: test
  script:
      - npm install --save-dev
      - make test-sqlite
  only:
      - master
  tags:
      - node

mysql:
  stage: test
  script:
      - npm install --save-dev
      - make test-mysql
  only:
      - master
  tags:
      - node

mariadb:
  stage: test
  script:
      - npm install --save-dev
      - make test-mariadb
  only:
      - master
  tags:
      - node

redis:
  stage: test
  script:
      - npm install --save-dev
      - make test-redis
  only:
      - master
  tags:
      - node

postgres:
  stage: test
  script:
      - npm install --save-dev
      - make test-postgres
  only:
      - master
  tags:
      - node

mongo:
  stage: test
  script:
      - npm install --save-dev
      - make test-mongo
  only:
      - master
  tags:
      - node

arango:
  stage: test
  script:
      - npm install --save-dev
      - make test-arango
  only:
      - master
  tags:
      - node

#all:
#  stage: test
#  script:
#      - npm install --save-dev
#      - make test
#  only:
#      - master
#  tags:
#      - node
