language: node_js

node_js:
  - 0.10
  - 0.12
  - 4.0
  
services:
    - mysql
    - postgresql
    - redis-server
    - mongodb
  
before_script:
    - mysql -e "CREATE USER 'test'@'%' IDENTIFIED BY 'test';" -uroot
    - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot
    - mysql -e "GRANT ALL PRIVILEGES ON test . * TO 'test'@'%';" -uroot
    - mysql -e "FLUSH PRIVILEGES;" -uroot
    - sleep 3
    - psql -c "CREATE ROLE test LOGIN ENCRYPTED PASSWORD 'test' NOINHERIT VALID UNTIL 'infinity';" -U postgres
    - psql -c "CREATE DATABASE test WITH ENCODING='UTF8' OWNER=test;" -U postgres
    - sleep 3
    - mongo test --eval 'db.addUser("test", "test");'
    - sleep 3
    - curl http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
    - echo "deb http://download.rethinkdb.com/apt precise main" | sudo tee -a /etc/apt/sources.list.d/rethinkdb.list
    - sudo apt-get update -qq
    - sudo apt-get install -y rethinkdb
    - sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/default.conf
    - sudo service rethinkdb restart